versions:
  - major: 13
    constraint: ~13.4.0
    destination: "13.4"
    template: ./updater/Dockerfile.tmpl
    templateData:
      PHP:
        Major: 8
        Minor: 4
      Debian: bookworm
  - major: 12
    constraint: ~12.4.0
    destination: "12.4"
    template: ./updater/Dockerfile.tmpl
    templateData:
      PHP:
        Major: 8
        Minor: 2
      Debian: bookworm
  - major: 11
    constraint: ~11.5.0
    destination: "11.5"
    template: ./updater/Dockerfile.tmpl
    templateData:
      PHP:
        Major: 8
        Minor: 2
      Debian: bookworm
  - major: 10
    constraint: ~10.4.0
    destination: "10.4"
    template: ./updater/Dockerfile.tmpl
    templateData:
      PHP:
        Major: 7
        Minor: 4
      Debian: buster
  - major: 9
    constraint: ^9.5
    destination: "9.5"
    template: ./updater/Dockerfile.tmpl
    templateData:
      PHP:
        Major: 7
        Minor: 4
      Debian: buster
  - major: 8
    constraint: ^8.7
    destination: "8.7"
    template: ./updater/Dockerfile.tmpl
    templateData:
      PHP:
        Major: 7
        Minor: 4
      Debian: buster