FROM php:PHPVER-apache
LABEL maintainer="Martin Helmich <typo3@martin-helmich.de>"

# Install TYPO3
RUN echo "deb http://deb.debian.org/debian stretch main" > /etc/apt/sources.list.d/stretch.list && \
    echo "Package: *\\nPin: release n=jessie\\nPin-Priority: 900\\n\\nPackage: libpcre3*\\nPin: release n=stretch\\nPin-Priority: 1000" > /etc/apt/preferences && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
# Configure PHP
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
        libxml2-dev \
        zlib1g-dev \
# Install required 3rd party tools
        graphicsmagick && \
# Fix outdated PCRE bug in Debian 8
    apt-get install -y -t stretch libpcre3 libpcre3-dev && \

# Configure extensions
    docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && \
    docker-php-ext-install -j$(nproc) mysqli soap gd zip opcache && \
    echo 'always_populate_raw_post_data = -1\nmax_execution_time = 240\nmax_input_vars = 1500\nupload_max_filesize = 32M\npost_max_size = 32M' > /usr/local/etc/php/conf.d/typo3.ini && \
# Configure Apache as needed
    a2enmod rewrite && \
    apt-get clean && \
    apt-get -y purge --auto-remove \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
        libxml2-dev \
        zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*

VOLUME /var/www/html

RUN set -ex; \
    curl -o typo3.tar.gz -fSL https://get.typo3.org/TYPOVER; \
    mkdir /usr/src/typo3; \
    tar -xzf typo3.tar.gz -C /usr/src/typo3; \
    rm typo3.tar.gz; \
    chown -R www-data:www-data /usr/src/typo3

COPY docker-entrypoint.sh /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["apache2-foreground"]
