name: Build and test TYPO3 7.6 image

on:
  push:
    paths:
      - '7.6/Dockerfile'
      - '7.6/docker-compose.yml'
  pull_request:
    paths:
      - '7.6/Dockerfile'
      - '7.6/docker-compose.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Build and start image
        run: |
          cd 7.6
          docker compose build
          docker compose up -d

          sleep 20

          curl -vLf http://localhost
          docker compose down -v
